### ISSUE TITLE
Problem with import py3

### ISSUE THREAD

**Issue by MrTheodor** [pdebuyl/pyh5md#12]
I am getting such error:
```
@lukrecja lennard_jones $ python lj_h5md.py 
Traceback (most recent call last):
  File "lj_h5md.py", line 5, in <module>
    import espressopp
  File "/home/teodor/project/phd/espressopp/sim-espressopp/espressopp/__init__.py", line 65, in <module>
    from espressopp import esutil, bc, storage, integrator, interaction, analysis, tools, standard_system, external, check, io
  File "/home/teodor/project/phd/espressopp/sim-espressopp/espressopp/analysis/__init__.py", line 68, in <module>
    from espressopp.analysis.PyStore import *
  File "/home/teodor/project/phd/espressopp/sim-espressopp/espressopp/analysis/PyStore.py", line 10, in <module>
    import pyh5md
  File "/home/teodor/.local/pyh5md/pdebuyl/lib/python2.7/site-packages/pyh5md/__init__.py", line 24, in <module>
    from core import *
  File "/home/teodor/.local/pyh5md/pdebuyl/lib/python2.7/site-packages/pyh5md/core.py", line 15, in <module>
    from pyh5md.utils import create_compact_dataset
  File "/home/teodor/.local/pyh5md/pdebuyl/lib/python2.7/site-packages/pyh5md/utils.py", line 19, in <module>
    from h5py._hl.base import HLObject, py3
ImportError: cannot import name py3
```

now when I remove that py3 import then everything is fine. I checked h5py/_hl/base.py and there is nothing like py3. Is it some compatibility tools for Python 3.x?

**Comment by pdebuyl** [comment]
The imports at the top of the file were taken from a corresponding h5py file that has changed since then. This can be cut.

**Comment by pdebuyl** [comment]
Also, I plan to update the code to a much simpler base: https://github.com/pdebuyl/pyh5md/tree/import_new_ph

**Comment by pdebuyl** [comment]
See #13
